-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK AS BOOK
LEFT OUTER JOIN AUTHOR AS AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
RIGHT OUTER JOIN BOOK_SALES AS BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC