-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE "%2022-01%"
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC
