-- 코드를 작성해주세요
# SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
# FROM ITEM_INFO AS A
# INNER JOIN ITEM_TREE AS B
# ON A.ITEM_ID = B.ITEM_ID
# # 전설이 아니거나 1이 아니거나
# WHERE A.RARITY = 'LEGEND' OR PARENT_ITEM_ID = '1'
# ORDER BY A.ITEM_ID DESC

# SELECT A.ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO AS A
# LEFT JOIN ITEM_TREE AS B
# ON A.ITEM_ID = B.ITEM_ID 
# AND B.PARENT_ITEM_ID IS NOT NULL
# WHERE B.ITEM_ID IS NULL
# ORDER BY A.ITEM_ID DESC

SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I 
LEFT JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
AND T.PARENT_ITEM_ID IS NOT NULL
WHERE T.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;