-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE * 30 * (1-DISCOUNT_RATE/100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
ON CAR.CAR_ID = HIS.CAR_ID
RIGHT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE

WHERE CAR.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    # 2022년 11월 1일 ~ 2022년 11월 30일까지 대여가능
                    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
                    ) AND PLAN.DURATION_TYPE = '30일 이상'
# 자동차 종류가 세단 또는 SUV
AND CAR.CAR_TYPE IN ('세단', 'SUV')
GROUP BY CAR.CAR_ID
# 30일간의 대여 금액이 50이상~200미만
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC