# 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR
# 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY
# 자동차 종류 별 대여 기간 종류 별 할인 정책 정보를 담은 CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# 세단, SUV
# 2022.11.1~2022.11.30
# 대여금액 50 <=  < 100
# 자동차 ID, 종류, 대여금액 (컬럼명 : FEE)
# 대여 금액을 기준으로 내림차순 정렬, 자동차 종류를 기준으로 오름차순 정렬, 자동차 ID를 기준으로 내림차순

SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (1-C.DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
RIGHT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND C.DURATION_TYPE='30일 이상'
GROUP BY A.CAR_ID
HAVING A.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC