-- 코드를 입력하세요
SELECT FOOD_TYPE,REST_ID, REST_NAME, FAVORITES  FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES)
IN (SELECT food_type, max(favorites) FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

# 한식 734 중식 20 일식 230 양식 102 분식 151