-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS AS INS
LEFT JOIN ANIMAL_OUTS AS OUTS
ON INS.NAME = OUTS.NAME
WHERE INS.SEX_UPON_INTAKE LIKE '%Intact%' and OUTS.SEX_UPON_OUTCOME LIKE ('%Spayed%') or '%Neutered%'
GROUP BY INS.NAME
ORDER BY INS.ANIMAL_ID