-- 코드를 입력하세요
-- REST_INFO // REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS, TEL

-- REST_REVIEW // REVIEW_ID, REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DATE

-- 최종 출력 : REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기 수, 주소, 리뷰 평균 점수
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A
INNER JOIN REST_REVIEW AS B
ON A.REST_ID = B.REST_ID
where ADDRESS like '서울%'
group by REST_ID
#having ADDRESS like '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC


# SELECT * FROM REST_INFO
# SELECT * FROM REST_REVIEW
# ORDER BY REST_ID DESC