-- 코드를 입력하세요
-- 0인 경우 남자, 1인 경우 여자

SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO AS A 
INNER JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE A.GENDER in ('0', '1')
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER