-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE,DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE from ANIMAL_INS ORDER BY ANIMAL_ID

-- 문제에서 ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE 이 출력되어야한다고 했다