-- 코드를 입력하세요
# ANIMAL_INS 동물 보호소에 들어온 동물의 정보를 담음
# ANIMAL_OUTS 동물 보호소에서 입양 보낸 동물의 정보를 담음
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS AS A
LEFT OUTER JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID is NULL
ORDER BY A.ANIMAL_ID


# SELECT OUTS.ANIMAL_ID, OUTS.NAME
# FROM ANIMAL_OUTS OUTS
# LEFT OUTER JOIN ANIMAL_INS INS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE INS.ANIMAL_ID is NULL
# ORDER BY OUTS.ANIMAL_ID
