-- 코드를 입력하세요
SELECT A.HISTORY_ID, 
     round(DAILY_FEE * (DATEDIFF(A.END_DATE,A.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"
FROM CAR_RENTAL_COMPANY_CAR AS B
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
ON A.CAR_ID = B.CAR_ID 
RIGHT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON B.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE LIKE '%트럭%'
GROUP BY A.HISTORY_ID
ORDER BY FEE DESC, A.HISTORY_ID DESC