-- 코드를 입력하세요
# 7월의 총 주문량 + 상반기의 총 주문량을 더한 값이 큰 순서대로 상휘 3개의 맛 출력

SELECT A.FLAVOR
FROM FIRST_HALF AS A
LEFT OUTER JOIN JULY AS B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER)+ B.TOTAL_ORDER DESC
LIMIT 3

# SELECT
# A.FLAVOR
# FROM
# JULY A
# INNER JOIN FIRSTHALF B
# ON A.FLAVOR = B.FLAVOR
# GROUP BY A.FLAVOR
# ORDER BY SUM(A.TOTALORDER) + B.TOTAL_ORDER DESC
# limit 3