-- 코드를 입력하세요
SELECT APP.APNT_NO, PA.PT_NAME, PA.PT_NO, APP.MCDP_CD, DOC.DR_NAME, APP.APNT_YMD
FROM APPOINTMENT AS APP
LEFT OUTER JOIN PATIENT AS PA
ON APP.PT_NO = PA.PT_NO
RIGHT OUTER JOIN DOCTOR AS DOC
ON APP.MDDR_ID = DOC.DR_ID
WHERE APP.MCDP_CD = 'CS' AND APP.APNT_CNCL_YMD IS NULL AND APP.APNT_YMD LIKE '2022-04-13%'
ORDER BY APP.APNT_YMD