-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME) BETWEEN '0' AND '23'
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR(DATETIME)

# SET @hour := -1;
# SELECT (@hour := @hour + 1) as HOUR,
# 	(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT 
# FROM ANIMAL_OUTS WHERE @hour < 23;
SET @HOUR := -1;
SELECT @HOUR := @HOUR + 1 AS HOUR,(SELECT COUNT(*)
                                  FROM ANIMAL_OUTS
                                  WHERE @HOUR = HOUR(DATETIME))
FROM ANIMAL_OUTS
WHERE @HOUR < 23

# 7 3
# 8 1
# 9 1
# 10 2
# 11 13
# 12 10
# 13 14
# 14 9
# 15 7
# 16 10
# 17 12
# 18 16
# 19 2