-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = '3' and TLNO != 'NULL' and GENDER = 'W'
ORDER BY MEMBER_ID 

# SELECT * FROM MEMBER_PROFILE
# WHERE GENDER = 'W'
# ORDER BY DATE_OF_BIRTH