-- 아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF 테이블
-- 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO 테이블

SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS A
INNER JOIN ICECREAM_INFO AS B
WHERE A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC