-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY in ('과자', '국', '김치', '식용유')
AND PRICE IN (SELECT max(price) FROM FOOD_PRODUCT GROUP BY CATEGORY)
ORDER BY PRICE DESC
# 식용유 8950 맛있는 마조유 
# 김치 19000 맛있는배추김치
# 국 2900 맛있는김치찌개
# 과자 1900 맛있는허니버터칩
